### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jungjaeeun** [jungjaeeun/janni_calendar#1]
- [x] 현재 선택된 날짜 표시
- [x] 토, 일 색상 다르게
- [ ] 달력 클릭 이벤트 추가
- [x] 반응형 스타일 수정

**Comment by jungjaeeun** [comment]
> * [x]  현재 선택된 날짜 표시
> * [x]  토, 일 색상 다르게
> * [ ]  달력 클릭 이벤트 추가
> * [x]  반응형 스타일 수정
